"""Initial news app tables

Revision ID: 7cf6f7b72b8b
Revises:
Create Date: 2025-08-01 18:55:04.811296+00:00

"""

from typing import Sequence, Union
from sqlmodel.sql.sqltypes import AutoString

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cf6f7b72b8b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", AutoString(length=255), nullable=False),
        sa.Column("description", AutoString(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("news_providers")
    # ### end Alembic commands ###
