#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

python << END
import asyncio
import sys
import time
import asyncpg

suggest_unrecoverable_after = 30
start = time.time()

async def wait_for_postgres():
    while True:
        try:
            conn = await asyncpg.connect(
                user="${POSTGRES_USER}",
                password="${POSTGRES_PASSWORD}",
                database="${POSTGRES_DB}",
                host="${POSTGRES_HOST}",
                port=${POSTGRES_PORT}
            )
            await conn.close()
            break
        except Exception as error:
            sys.stderr.write("Waiting for PostgreSQL to become available...\n")
            if time.time() - start > suggest_unrecoverable_after:
                sys.stderr.write(
                    f"  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{error}'\n"
                )
            await asyncio.sleep(1)

asyncio.run(wait_for_postgres())
END

>&2 echo 'PostgreSQL is available'

exec "$@"
