#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd /app/src
exec celery --app=core.celery_app:celery_app --quiet beat \
    --loglevel="${LOG_LEVEL:-INFO}" \
    --scheduler=core.celery_scheduler:DatabaseScheduler
