#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd src

if [ "${DEBUGPY:-false}" = "true" ]; then
    exec python -m debugpy --listen 0.0.0.0:5678 -m uvicorn main:app \
        --host 0.0.0.0 \
        --port 8000
else
    exec python -m fastapi dev main.py \
        --host 0.0.0.0 \
        --port 8000 \
        --reload
fi
