from copy import deepcopy
from pathlib import Path
from typing import Any

import yaml
from fastapi import FastAPI, HTTPException, Request, status
from fastapi.openapi.docs import get_redoc_html, get_swagger_ui_html
from fastapi.responses import HTMLResponse, JSONResponse, Response

from core.i18n import _, resolve_language, translate
from core.settings import settings

LOCALIZED_SCHEMA_KEYS = frozenset({"description", "summary", "title"})
DOCS_ASSETS_DIRECTORY = Path(__file__).resolve().parents[1] / "static" / "docs"
DOCS_ASSET_MEDIA_TYPES = {
    "redoc/redoc.standalone.js": "text/javascript",
    "swagger-ui/favicon-32x32.png": "image/png",
    "swagger-ui/swagger-ui-bundle.js": "text/javascript",
    "swagger-ui/swagger-ui.css": "text/css",
}
HTTP_OPERATION_METHODS = frozenset({"delete", "get", "patch", "post", "put"})
CLIENT_DATE_RESPONSE_HEADERS: dict[str, dict[str, Any]] = {
    "X-Client-Date-Status": {
        "description": _(
            "Optional client Date reading: available, unavailable, or invalid. No request is rejected for this diagnostic."
        ),
        "schema": {"type": "string", "enum": ["available", "unavailable", "invalid"]},
    },
    "X-Client-Date-Delta-Seconds": {
        "description": _(
            "Signed server receipt minus client Date in seconds; includes transit and generation delay, so it is not exact clock skew."
        ),
        "schema": {"type": "integer"},
    },
    "X-Client-Date-Advisory": {
        "description": _(
            "Present as check-device-time only when the configured apparent difference threshold is reached."
        ),
        "schema": {"type": "string", "enum": ["check-device-time"]},
    },
    "X-Server-Received-At": {
        "description": _(
            "Server UTC receipt timestamp. Response Date, when present, is generated by the HTTP server or proxy."
        ),
        "schema": {"type": "string", "format": "date-time"},
    },
}
SHARED_INPUT_HEADERS: dict[str, dict[str, Any]] = {
    "Date": {
        "description": _(
            "Optional RFC 9110 HTTP-date generated by native clients for advisory diagnostics. Browser JavaScript cannot set Date. Missing or invalid values do not reject the request."
        ),
        "schema": {"type": "string", "maxLength": 128},
        "example": "Mon, 28 Sep 2026 12:00:00 GMT",
    },
    "Accept-Language": {
        "description": _(
            "Optional preferred response language. English and Farsi are supported; regional tags use their base language and unsupported values fall back to English."
        ),
        "schema": {"type": "string"},
        "example": "fa-IR",
    },
    "X-Request-ID": {
        "description": _(
            "Optional UUIDv7 correlation identifier. Missing or invalid values are replaced with a generated UUIDv7; the effective value is returned in X-Request-ID."
        ),
        "schema": {"type": "string"},
    },
    "X-Audit-Reason": {
        "description": _(
            "Optional caller-supplied reason recorded in audit history. It is not an authorization credential."
        ),
        "schema": {"type": "string"},
        "example": "Correcting a submitted request",
    },
}

SWAGGER_OPERATION_SORTER_MARKER = '"operationsSorter": "subjectCrudOrder"'
SWAGGER_OPERATION_SORTER = """"operationsSorter": (left, right) => {
        const rank = (operation) => {
            const path = operation.get("path");
            const method = operation.get("method");
            if (path.endsWith("/search")) return 0;
            if (method === "get" && path.includes("{") && !path.endsWith("/download")) return 1;
            if (path.endsWith("/history")) return 2;
            if (path.endsWith("/report")) return 3;
            if (method === "post" && !path.includes("{")) return 4;
            if (method === "put" || method === "patch") return 5;
            if (method === "delete") return 6;
            return 7;
        };
        return rank(left) - rank(right)
            || left.get("path").localeCompare(right.get("path"))
            || left.get("method").localeCompare(right.get("method"));
    }"""


def _subject_tag(path: str) -> str:
    """Return the Swagger subject owning an API path."""
    relative_path = path.removeprefix(settings.API_V1_STR).strip("/")
    parts = relative_path.split("/")
    root = parts[0]
    child = parts[1] if len(parts) > 1 else ""

    if root == "admin":
        return child
    if root == "me" and child in {"saved-views", "favorites"}:
        return child
    if root == "designer":
        return "definition-library" if child == "library" else "designer"
    if root == "auth" and child in {"permissions", "sessions"}:
        return child
    if root == "media" and child in {"files", "images"}:
        return child
    if root == "support":
        return "support-incidents"
    if root == "calendar":
        return "calendar-events"
    if root == "tasks":
        if child in {"definitions", "executions", "schedules"}:
            return f"task-{child}"
        return "task-executions"
    if root in {"health", "ready", "internal"}:
        return "health"
    return root


def _group_openapi_operations_by_subject(schema: dict[str, Any]) -> dict[str, Any]:
    """Assign one subject tag to each operation and retain only used tag metadata."""
    used_tags: set[str] = set()
    for path, path_item in schema.get("paths", {}).items():
        subject = _subject_tag(path)
        for method, operation in path_item.items():
            if method not in HTTP_OPERATION_METHODS:
                continue
            operation["tags"] = [subject]
            parameters = operation.setdefault("parameters", [])
            documented_headers = {
                parameter.get("name", "").lower()
                for parameter in parameters
                if parameter.get("in") == "header"
            }
            for name, details in SHARED_INPUT_HEADERS.items():
                if name.lower() not in documented_headers:
                    parameters.append({"name": name, "in": "header", "required": False, **details})
            for status_code, response in operation.get("responses", {}).items():
                if status_code.startswith("2"):
                    response.setdefault("headers", {}).update(
                        deepcopy(CLIENT_DATE_RESPONSE_HEADERS)
                    )
            used_tags.add(subject)
    schema["tags"] = [tag for tag in settings.OPENAPI_TAGS if tag["name"] in used_tags]
    return schema


def _translate_schema(value: Any, language: str, parent_key: str | None = None) -> Any:
    """Translate human-readable OpenAPI values while preserving identifiers."""
    if isinstance(value, dict):
        return {key: _translate_schema(item, language, key) for key, item in value.items()}
    if isinstance(value, list):
        return [_translate_schema(item, language, parent_key) for item in value]
    if isinstance(value, str) and parent_key in LOCALIZED_SCHEMA_KEYS:
        return translate(value, language)
    return value


def localized_openapi(app: FastAPI, language: str) -> dict[str, Any]:
    """Return an isolated OpenAPI document translated from gettext catalogs."""
    selected = resolve_language(language)
    schema = _translate_schema(deepcopy(app.openapi()), selected)
    schema["x-docs-language"] = selected
    return schema


def configure_localized_docs(app: FastAPI) -> None:
    """Install language-aware Swagger and OpenAPI routes on an application."""
    fastapi_openapi = app.openapi

    def subject_grouped_openapi() -> dict[str, Any]:
        """Return FastAPI's generated schema with subject-oriented operation metadata."""
        return _group_openapi_operations_by_subject(fastapi_openapi())

    app.openapi = subject_grouped_openapi  # ty: ignore[invalid-assignment]
    docs_assets = {
        path: ((DOCS_ASSETS_DIRECTORY / path).read_bytes(), media_type)
        for path, media_type in DOCS_ASSET_MEDIA_TYPES.items()
    }

    @app.get(f"{settings.DOCS_ASSETS_URL}/{{asset_path:path}}", include_in_schema=False)
    async def docs_asset(asset_path: str) -> Response:
        """Serve only the pinned documentation assets bundled with the application."""
        asset = docs_assets.get(asset_path)
        if asset is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND)
        content, media_type = asset
        return Response(
            content=content,
            media_type=media_type,
            headers={"Cache-Control": "public, max-age=31536000, immutable"},
        )

    @app.get(settings.DOCS_URL, include_in_schema=False)
    async def swagger_docs(request: Request) -> HTMLResponse:
        """Serve Swagger using the browser's preferred supported language."""
        language = resolve_language(request.headers.get("Accept-Language"))
        response = get_swagger_ui_html(
            openapi_url=settings.OPENAPI_URL,
            title=f"{settings.PROJECT_NAME} — {language.upper()}",
            swagger_js_url=f"{settings.DOCS_ASSETS_URL}/swagger-ui/swagger-ui-bundle.js",
            swagger_css_url=f"{settings.DOCS_ASSETS_URL}/swagger-ui/swagger-ui.css",
            swagger_favicon_url=f"{settings.DOCS_ASSETS_URL}/swagger-ui/favicon-32x32.png",
            init_oauth=settings.SWAGGER_UI_INIT_OAUTH,
            swagger_ui_parameters=settings.SWAGGER_UI_PARAMETERS,
        )
        response = HTMLResponse(
            bytes(response.body)
            .decode()
            .replace(
                SWAGGER_OPERATION_SORTER_MARKER,
                SWAGGER_OPERATION_SORTER,
            )
        )
        response.headers["Content-Language"] = language
        response.headers["Vary"] = "Accept-Language"
        return response

    @app.get(settings.REDOC_URL, include_in_schema=False)
    async def redoc_docs(request: Request) -> HTMLResponse:
        """Serve ReDoc using the browser's preferred supported language."""
        language = resolve_language(request.headers.get("Accept-Language"))
        response = get_redoc_html(
            openapi_url=settings.OPENAPI_URL,
            title=f"{settings.PROJECT_NAME} — {language.upper()} — ReDoc",
            redoc_js_url=f"{settings.DOCS_ASSETS_URL}/redoc/redoc.standalone.js",
            redoc_favicon_url=f"{settings.DOCS_ASSETS_URL}/swagger-ui/favicon-32x32.png",
            with_google_fonts=False,
        )
        response.headers["Content-Language"] = language
        response.headers["Vary"] = "Accept-Language"
        return response

    @app.get(settings.OPENAPI_URL, include_in_schema=False)
    async def openapi_document(request: Request) -> JSONResponse:
        """Return the OpenAPI schema in the preferred request language."""
        language = resolve_language(request.headers.get("Accept-Language"))
        return JSONResponse(
            localized_openapi(app, language),
            headers={"Content-Language": language, "Vary": "Accept-Language"},
        )

    @app.get(settings.OPENAPI_YAML_URL, include_in_schema=False)
    async def openapi_yaml_document(request: Request) -> Response:
        """Return the generated OpenAPI schema as YAML in the preferred language."""
        language = resolve_language(request.headers.get("Accept-Language"))
        content = yaml.safe_dump(
            localized_openapi(app, language),
            allow_unicode=True,
            sort_keys=False,
        )
        return Response(
            content=content,
            media_type="application/yaml",
            headers={"Content-Language": language, "Vary": "Accept-Language"},
        )
